#ifndef _SANDBOX_PRIVATE_H_
#define _SANDBOX_PRIVATE_H_
#include <sandbox.h>
enum sandbox_filter_type {
    SANDBOX_FILTER_NONE = 0, SANDBOX_FILTER_PATH = 1,
    SANDBOX_FILTER_GLOBAL_NAME = 2, SANDBOX_FILTER_LOCAL_NAME = 3,
    SANDBOX_FILTER_APPLEEVENT_DESTINATION = 4, SANDBOX_FILTER_RIGHT_NAME = 5,
    SANDBOX_FILTER_PREFERENCE_DOMAIN = 6, SANDBOX_FILTER_KEXT_BUNDLE_ID = 7,
    SANDBOX_FILTER_INFO_TYPE = 8, SANDBOX_FILTER_NOTIFICATION = 9,
    SANDBOX_FILTER_XPC_SERVICE_NAME = 10, SANDBOX_FILTER_IOKIT_CONNECTION = 11,
    SANDBOX_FILTER_SYSCALL_NUMBER = 128,
};
#define SANDBOX_CHECK_NO_REPORT 0x0001
int sandbox_check(pid_t pid, const char *operation, enum sandbox_filter_type type, ...);
#endif
